{
  Interstellar: "No";
  accept: null;
  acceptTerms: null;
  accessories: "";
  ammountOnDocument: "";
  bat: null;
  batDescription: null;
  bodywork: "Yes";
  brandandmodel: "fdsa";
  city: "delhi";
  consignment: "No";
  country: "United States";
  created_at: "2022-11-16T17:56:52.000000Z";
  dealerDescription: "";
  dealerId: "No";
  dealerName: "ervice records for recent and/or notable services.";
  deleted_at: null;
  description: "http://shibnobimotors.s3-website-us-east-1.amazonaws.com/vechiles";
  detailvin: null;
  documentFee: 3322;
  done: 1;
  email: "";
  engineSize: "No";
  flag: null;
  hereFrom: "ervice records for recent and/or notable services.";
  id: 2;
  interior: "No";
  issuesorproblems: "no history";
  km: "the seller's name";
  kmacc: "clean";
  link: "";
  make: "Tata";
  membership: "Are you ";
  model: "Nexon";
  modificationstock: "No";
  moreDescription: "ervice records for recent and/or notable services.";
  name: "Nexon";
  odmeter: "132233";
  ogEngine: "";
  owned: "No";
  ownerDetail: "No ";
  pickOne: null;
  premium: 1;
  reservAmount: null;
  reserve: "No";
  rustpresent: "Yes";
  servicesperformed: null;
  sizetires: "dsaf";
  state: null;
  stepFourImage: null;
  stepOneImage: "./upload/vehicles//Vehicle-1668621413.jpg";
  stepThreeImage: null;
  stepTwoImage: "";
  title: "";
  titleStatus: "engion";
  transmission: "http://shibnobimotors.s3-website-us-east-1.amazonaws.com/vechiles";
  truckDetails: null;
  truckfromnew: null;
  understand: null;
  understandCondition: null;
  updated_at: "2022-11-16T17:56:53.000000Z";
  userId: 1;
  year: "2018";
  message: "success";
  status: 200;
}
{
  Interstellar: "No";
  accept: null;
  acceptTerms: "1";
  accessories: "Service Records,window sticky,Spare Parts,Owner's Manual,car cover";
  ammountOnDocument: "";
  bat: null;
  batDescription: null;
  bodywork: "Yes";
  brandandmodel: "fdsa";
  city: "delhi";
  consignment: "Yes";
  country: "Austria";
  created_at: "2022-11-21T12:41:16.000000Z";
  dealerDescription: "What is the name of your dealership";
  dealerId: "Yes";
  dealerName: "sdaf";
  deleted_at: null;
  description: "sadffsd";
  detailvin: null;
  documentFee: 2100;
  done: 1;
  email: "";
  engineSize: "Yes";
  flag: null;
  hereFrom: "dsafsd";
  id: 15;
  interior: "No";
  issuesorproblems: "fsda";
  km: "24110";
  kmacc: "No";
  link: "";
  make: "LX";
  membership: "Are you ";
  model: "Nexon";
  modificationstock: "No";
  moreDescription: "dsaf";
  name: "USER";
  odmeter: "24110";
  ogEngine: "";
  owned: "Yes";
  ownerDetail: "No ";
  pickOne: "18 machine-finished alloy wheels";
  premium: 1;
  reservAmount: null;
  reserve: "No";
  rustpresent: "Yes";
  servicesperformed: null;
  sizetires: "304/E23";
  state: null;
  stepFourImage: null;
  stepOneImage: "./upload/vehicles//Vehicle-1669034476.jpg";
  stepThreeImage: null;
  stepTwoImage: "";
  title: "";
  titleStatus: "fdsafdsa";
  transmission: "http://shibnobimotors.s3-website-us-east-1.amazonaws.com/vechiles";
  truckDetails: "Illumination,Soft tonneau cover,Kicker audio system with MultiPro tailgate,Power-retractable tonneau cover";
  truckfromnew: null;
  understand: null;
  understandCondition: "1";
  updated_at: "2022-11-21T12:41:17.000000Z";
  userId: 34;
  year: "2018";
  message: "success";
  status: 200;
}
