// import React, { useEffect, useState } from "react";
// import { AutoComplete } from "antd";
// import { Link } from "react-router-dom";
// import { useSelector } from "react-redux";
// const data = [
//   {
//     id: 1,
//     name: "List Your Vehicle",
//     desc: "sohan is a good boy",
//     redirect: "/submit",
//   },
//   {
//     id: 2,
//     name: "Showrooms",
//     desc: "mohan is a good boy",
//     redirect: "/showroom",
//   },
//   { id: 3, name: "Raffle", desc: "lalu is a good boy", redirect: "/carraffle" },
//   {
//     id: 4,
//     name: "Feautres",
//     desc: "modi is a good boy",
//     redirect: "/feautres",
//   },
//   {
//     id: 5,
//     name: "Charity Actions",
//     desc: "sohan is a good boy",
//     redirect: "/charity",
//   },
//   {
//     id: 6,
//     name: "About",
//     desc: "sohan is a good boy",
//     redirect: "/aboutshibnobi",
//   },
//   { id: 7, name: "Faq", desc: "sohan is a good boy", redirect: "/faq" },
//   { id: 8, name: "Store", desc: "sohan is a good boy", redirect: "/shop" },
// ];

// const Searchbar = () => {
//   const logingUser = useSelector((state) => state);
//   console.log(logingUser.submitvechilesReducer.vehicleData);
//   const [options, setOptions] = useState([]);
//   const [searchData, setSearchData] = useState([]);
//   const [filterData, setFilterData] = useState([]);
//   const [searchValue, setSearchValue] = useState("");

//   const handleSearch = (value) => {
//     console.log(11, logingUser.submitvechilesReducer.vehicleData);
//     let data = logingUser.submitvechilesReducer.vehicleData
//       .filter((ele) => ele.name !== null && ele.name.includes(value))
//       .map((value) => value);
//     console.log(12, data);
//     // setFilterData(data);

//     setSearchValue(value);
//     setOptions(data);
//   };
//   const onSelect = (value) => {
//     console.log("onSelect", value);
//   };

//   const searchResult = () =>
//     filterData.length > 0 &&
//     filterData.map((curElem, i) => {
//       const category = `${curElem.id}`;
//       return {
//         value: category,
//         label: <span style={{ color: "#fff" }}>sdfsdfsdfsd</span>,
//       };
//     });

//   return (
//     <div className="searchX">
//       <AutoComplete
//         dropdownMatchSelectWidth={252}
//         className="searchSec"
//         options={options}
//         onSelect={onSelect}
//         onSearch={handleSearch}
//         placeholder="Search.."
//       />
//       <i className="fa-solid fa-magnifying-glass"></i>
//     </div>
//   );
// };
// export default Searchbar;

import React, { useState } from "react";
import { AutoComplete, Input } from "antd";
import { Link } from "react-router-dom";
const data = [
  {
    id: 6,
    userId: 8,
    name: "Rishabh",
    year: "2019",
    make: "Audi",
    description: "ftuit6i6i",
    model: "Afour",
    owned: "No",
    country: "Azerbaijan",
    state: null,
    city: "goa",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "21000",
    kmacc: "Yes",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "./upload/vehicles//Vehicle-1672383763.jpg",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "car cover",
    moreDescription: "og87h",
    reserve: "No",
    hereFrom: "iugo7o",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2022-12-30T07:02:39.000000Z",
    updated_at: "2023-01-07T14:11:08.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 2000,
    consignment: "No",
    email: "rishabh@gmail.com",
    odmeter: "21000",
    Interstellar: "Yes",
    interior: "No",
    brandandmodel: "Audi",
    sizetires: "305/13RI",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "goyo7",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/4, 12:34:20",
    pickOne: "Alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "11",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "",
    desc1: "",
    desc2: "",
    currentAmount: {
      id: 7,
      userId: 16,
      auctionId: "6",
      auctionAmmount: "4500000",
      flag: 1,
      created_at: "2022-12-30 10:11:52",
      updated_at: "2022-12-30 10:11:52",
      deleted_at: null,
      vehicle_id: "6",
      comment: null,
    },
    view: 1,
    like: 1,
    status: {
      id: 11,
      title: "Rejected",
      desc: "",
      param1: "",
      param2: "",
      param3: "",
      param4: "",
    },
  },
  {
    id: 7,
    userId: 8,
    name: "Roshan",
    year: "2019",
    make: "bmw",
    description: "gfctgkcf",
    model: "1321",
    owned: "No",
    country: "Azerbaijan",
    state: null,
    city: "goa",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "21000",
    kmacc: "Yes",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "./upload/vehicles//Vehicle-1672401524.jpg",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records,Owner's Manual",
    moreDescription: "gjvbyu",
    reserve: "No",
    hereFrom: "bvjhbgvh",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2022-12-30T11:58:42.000000Z",
    updated_at: "2023-01-07T14:08:14.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 2000,
    consignment: "No",
    email: "tghfctgfcy@fbnuj",
    odmeter: "21000",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "guik",
    sizetires: "guib",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "gvbjb",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/4, 17:30:23",
    pickOne: "Alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "CNG",
    approved: null,
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "",
    desc1: "",
    desc2: "",
    currentAmount: {
      id: 8,
      userId: 9,
      auctionId: "7",
      auctionAmmount: "2500",
      flag: 1,
      created_at: "2022-12-30 12:44:33",
      updated_at: "2022-12-30 12:44:33",
      deleted_at: null,
      vehicle_id: "7",
      comment: null,
    },
    view: 1,
    like: 0,
    status: null,
  },
  {
    id: 8,
    userId: 9,
    name: "user",
    year: "2015",
    make: "fsdfdsfsafad",
    description: "Please provide any links to videos",
    model: "GT-9",
    owned: "Yes",
    country: "Algeria",
    state: null,
    city: "delhi",
    bat: null,
    batDescription: null,
    dealerName: "What is the name of your dealership",
    dealerId: "Yes",
    dealerDescription: "What is the name of your dealership",
    ownerDetail: "Race Car ",
    km: "51000",
    kmacc: "Yes",
    ogEngine: "",
    transmission:
      "http://shibnobimotors.s3-website-us-east-1.amazonaws.com/vechiles",
    title: "",
    titleStatus:
      "What has changed on this vehicle since it was last listed on Gas guzzlrs",
    engineSize: "Yes",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories:
      "window sticky,Service Records,car cover,Owner's Manual,Spare Parts,Other",
    moreDescription:
      "Dates and timelines provide valuable information for interested buyers. Don't forget to upload images of redacted service records for recent and/or notable services.",
    reserve: "Yes",
    hereFrom:
      "What issues or problems does it currently have? Is there anything that currently doesn't work or doesn't operate correctly? Be thorough - you don't want commenters to do this for you.",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2022-12-30T14:44:58.000000Z",
    updated_at: "2022-12-30T14:44:58.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 500,
    consignment: "Yes",
    email: "user@gmail.com",
    odmeter: "51000",
    Interstellar: "Yes",
    interior: "Yes",
    brandandmodel: "MRF",
    sizetires: "304/E23",
    detailvin: null,
    bodywork: "Yes",
    rustpresent: "Yes",
    modificationstock: "Yes",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems:
      "What do you know about the history of the vehicle from new",
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: "",
    EndTime: "12/2/2022, 12:09:36 PM",
    pickOne: "tvs wheels",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "yes  engion changed",
    rustDetails: "no rust",
    truckHistory: "no history",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: "Yes",
    fuel: "CNG",
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 9,
    userId: 1,
    name: "sonu",
    year: "2020",
    make: "oddi",
    description: "fgsgfgsfgsdfg",
    model: "bmw",
    owned: "No",
    country: "Australia",
    state: null,
    city: "usa",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "Race Car ",
    km: "2343",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories:
      "window sticky,Service Records,car cover,Owner's Manual,Spare Parts,Other",
    moreDescription: "ggfdgfdg",
    reserve: "No",
    hereFrom: "jhjkhkhjkhjk",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-02T06:15:32.000000Z",
    updated_at: "2023-01-03T10:15:20.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 325,
    consignment: "No",
    email: "hello@gmail.com",
    odmeter: "2343",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "dfggfhj",
    sizetires: "fghg",
    detailvin: null,
    bodywork: "Yes",
    rustpresent: "Yes",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "wrerrytrytbcvbc",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/7, 11:45:31",
    pickOne: "gfdghg",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "rererer",
    truckHistory: "sdfgdghgj",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: null,
    sold: "1",
    displayInAuction: "No",
    auctionType: "",
    desc1: "my name is kesav",
    desc2: "my designation is software developer",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 10,
    userId: 9,
    name: "komal",
    year: "2022",
    make: "BMW",
    description: "hello  gas guzzlrs",
    model: "1212",
    owned: "No",
    country: "Australia",
    state: null,
    city: "india",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "2343",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "window sticky",
    moreDescription: "kdkdkddkd",
    reserve: "No",
    hereFrom: "hghghg",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-02T06:38:20.000000Z",
    updated_at: "2023-01-02T06:38:20.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 234,
    consignment: "No",
    email: "kkk@gmail.com",
    odmeter: "2343",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "wqwqw",
    sizetires: "fghg",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "vgvgvgvg",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/7, 12:8:18",
    pickOne: "rteretrt",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "CNG",
    approved: "1",
    sold: "1",
    displayInAuction: "No",
    auctionType: "",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: {
      id: 1,
      title: "Approved",
      desc: "",
      param1: "",
      param2: "",
      param3: "",
      param4: "",
    },
  },
  {
    id: 11,
    userId: 1,
    name: "bablu",
    year: "2022",
    make: "saffari",
    description: "xdxdxd",
    model: "awawaw",
    owned: "No",
    country: "Bangladesh",
    state: null,
    city: "INDIA",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "5656",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "window sticky",
    moreDescription: "gtyuhhb789",
    reserve: "No",
    hereFrom: "nknkn",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-02T06:56:06.000000Z",
    updated_at: "2023-01-02T06:56:06.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 231,
    consignment: "No",
    email: "g@gmail.com",
    odmeter: "5656",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "mkmkmk",
    sizetires: "dfdfdf",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "klklk",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/7, 12:26:5",
    pickOne: "alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "Premium listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 1,
    like: 1,
    status: null,
  },
  {
    id: 12,
    userId: 8,
    name: "motorola",
    year: "2018",
    make: "bettle",
    description: "fuyhvyhu",
    model: "coopeer",
    owned: "No",
    country: "Austria",
    state: null,
    city: "goaa",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "22000",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records",
    moreDescription: "fyukvyh",
    reserve: "No",
    hereFrom: "cftgcrtg",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-02T12:00:18.000000Z",
    updated_at: "2023-01-02T12:00:18.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 2500,
    consignment: "No",
    email: "keshav@gmail.com",
    odmeter: "22000",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "audi",
    sizetires: "205/12rt",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "ygfvuh",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/7, 17:32:5",
    pickOne: "fe44t45",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "For charity",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 13,
    userId: 9,
    name: "raja",
    year: "2015",
    make: "santro",
    description: "vimo",
    model: "santro250",
    owned: "Yes",
    country: "Bahamas",
    state: null,
    city: "govindpuram",
    bat: null,
    batDescription: null,
    dealerName: "sobhit",
    dealerId: "Yes",
    dealerDescription: "sobhit",
    ownerDetail: "Race Car ",
    km: "2000",
    kmacc: "Yes",
    ogEngine: "",
    transmission: "http://localhost:3000/vechiles",
    title: "",
    titleStatus: "this is best vehicle",
    engineSize: "Yes",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "window sticky",
    moreDescription: "fgssg2017",
    reserve: "Yes",
    hereFrom: "what isses and problem",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-03T11:45:48.000000Z",
    updated_at: "2023-01-03T11:50:17.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 200,
    consignment: "Yes",
    email: "ks@gmail.com",
    odmeter: "2000",
    Interstellar: "Yes",
    interior: "Yes",
    brandandmodel: "brand and model",
    sizetires: "25/26 ",
    detailvin: null,
    bodywork: "Yes",
    rustpresent: "Yes",
    modificationstock: "Yes",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "new vehicle  textarea",
    accept: null,
    understand: null,
    reservAmount: 20,
    truckDetails: "",
    EndTime: "2023/1/8, 17:15:48",
    pickOne: "alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "modifi details sss",
    rustDetails: "rustdetailsv",
    truckHistory: "trukhistory or body",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: null,
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "Premium listing",
    desc1: "correct",
    desc2: "correct22",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 14,
    userId: 8,
    name: "Roshan",
    year: "2013",
    make: "ygfyt",
    description: "esrrser",
    model: "uygyu",
    owned: "No",
    country: "Bahrain",
    state: null,
    city: "yfufg",
    bat: null,
    batDescription: null,
    dealerName: "fyhfgvy",
    dealerId: "Yes",
    dealerDescription: "fyhfgvy",
    ownerDetail: "No ",
    km: "23244",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "car cover",
    moreDescription: "ghhj",
    reserve: "Yes",
    hereFrom: "73677",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-04T06:32:26.000000Z",
    updated_at: "2023-01-04T06:32:26.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 54457,
    consignment: "No",
    email: "rosia@gmail.com",
    odmeter: "23244",
    Interstellar: "Yes",
    interior: "No",
    brandandmodel: "dyffikd",
    sizetires: "205/12rtred",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "yufgyu",
    accept: null,
    understand: null,
    reservAmount: 3000,
    truckDetails: "",
    EndTime: "2023/1/9, 12:4:16",
    pickOne: "Alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "1",
    sold: "1",
    displayInAuction: "No",
    auctionType: "General listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: {
      id: 1,
      title: "Approved",
      desc: "",
      param1: "",
      param2: "",
      param3: "",
      param4: "",
    },
  },
  {
    id: 15,
    userId: 8,
    name: "ROSHAN",
    year: "2020",
    make: "BMW",
    description: "KLJMIOPJ",
    model: "RED",
    owned: "No",
    country: "Bahamas",
    state: null,
    city: "DRTCT",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "21000",
    kmacc: "Yes",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records,Spare Parts",
    moreDescription: "U8H",
    reserve: "No",
    hereFrom: "UIOHNUIH",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-04T12:12:33.000000Z",
    updated_at: "2023-01-04T12:12:33.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 12200,
    consignment: "No",
    email: "RJEIO@GMAIL",
    odmeter: "21000",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "Audi",
    sizetires: "205/12rtred",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "YHGFYU",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/9, 17:44:24",
    pickOne: "dytkd",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "General listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 1,
    like: 0,
    status: null,
  },
  {
    id: 16,
    userId: 8,
    name: "RAHUL",
    year: "2020",
    make: "AUDI",
    description: "TYYYYJH",
    model: "BLUE",
    owned: "No",
    country: "Bahrain",
    state: null,
    city: "YGVFYKUGVB",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "6667",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "window sticky",
    moreDescription: "DEFGRG",
    reserve: "No",
    hereFrom: "DFFG",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-04T12:24:27.000000Z",
    updated_at: "2023-01-04T12:24:27.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 1111100,
    consignment: "No",
    email: "DWDWD@FDEF",
    odmeter: "6667",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "audi",
    sizetires: "205/12rtuk",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "FRTT",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/9, 17:56:18",
    pickOne: "Alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "For charity",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 17,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: "./upload/vehicles//Vehicle-1672914882.jpg",
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-05T10:34:47.000000Z",
    updated_at: "2023-01-05T10:34:47.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 18,
    userId: 8,
    name: "sunil",
    year: "2014",
    make: "Astar",
    description: "rtgrg",
    model: "1234",
    owned: "No",
    country: "Azerbaijan",
    state: null,
    city: "goa",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "22000",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records",
    moreDescription: "sderfdf",
    reserve: "No",
    hereFrom: "ddftfgg",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-06T07:04:24.000000Z",
    updated_at: "2023-01-06T07:04:24.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 2500,
    consignment: "No",
    email: "sunil@hotm.vom",
    odmeter: "22000",
    Interstellar: "Yes",
    interior: "Yes",
    brandandmodel: "audi",
    sizetires: "205/12rtuk",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "dtfgg",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/11, 12:36:19",
    pickOne: "tfiiiyf",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "General listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 19,
    userId: 9,
    name: "user",
    year: "2013",
    make: "bmw",
    description: "kfdlsjflka",
    model: "nehi pata",
    owned: "Yes",
    country: "Australia",
    state: null,
    city: "delhi",
    bat: null,
    batDescription: null,
    dealerName: "Mohan dealer",
    dealerId: "Yes",
    dealerDescription: "Mohan dealer",
    ownerDetail: "Race Car ",
    km: "5465",
    kmacc: "Yes",
    ogEngine: "",
    transmission:
      "https://in.search.yahoo.com/search?fr=mcafee&type=E211IN826G0&p=how+to+validate+vin+number",
    title: "",
    titleStatus: "fkldsjkla",
    engineSize: "Yes",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records,Spare Parts,Owner's Manual",
    moreDescription: "fdsafsa",
    reserve: "Yes",
    hereFrom: "dfsasa",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-06T07:12:43.000000Z",
    updated_at: "2023-01-06T07:12:43.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 200,
    consignment: "Yes",
    email: "user@gmail.com",
    odmeter: "5465",
    Interstellar: "Yes",
    interior: "Yes",
    brandandmodel: "MRF",
    sizetires: "304/E23",
    detailvin: null,
    bodywork: "Yes",
    rustpresent: "Yes",
    modificationstock: "Yes",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "fdasf",
    accept: null,
    understand: null,
    reservAmount: 2000,
    truckDetails: "",
    EndTime: "2023/1/11, 12:42:41",
    pickOne: "tvs wheels",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "yes  engion changed",
    rustDetails: "no rust",
    truckHistory: "no history",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Electric",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "General listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 20,
    userId: 8,
    name: "devdas",
    year: "2018",
    make: "mercedes",
    description: "bvfdfgrg",
    model: "asdf",
    owned: "No",
    country: "Albania",
    state: null,
    city: "qwerty",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "22000",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "./upload/vehicles//Vehicle-1672993605.jpg",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records",
    moreDescription: "sdxdswd",
    reserve: "No",
    hereFrom: "fergfg",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-06T08:26:42.000000Z",
    updated_at: "2023-01-06T08:26:45.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 2500,
    consignment: "No",
    email: "redr@fedf.gf",
    odmeter: "22000",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "audi",
    sizetires: "205/12rt",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "tthgtgh",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/11, 13:58:36",
    pickOne: "Alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "Premium listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 21,
    userId: 8,
    name: "damon",
    year: "2017",
    make: "vamp",
    description: "fdff",
    model: "hybrid",
    owned: "No",
    country: "Azerbaijan",
    state: null,
    city: "delhi",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "Race Car ",
    km: "22000",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records",
    moreDescription: "grrg",
    reserve: "No",
    hereFrom: "fdf",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-06T09:41:47.000000Z",
    updated_at: "2023-01-06T09:41:47.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 15000,
    consignment: "Yes",
    email: "desedr@grfg.cg",
    odmeter: "22000",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "Audi",
    sizetires: "we3435",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "dfede",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/11, 15:13:43",
    pickOne: "dytkd",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "General listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 22,
    userId: 8,
    name: "stefan",
    year: "2012",
    make: "msutng",
    description: "cfsefdefe",
    model: "gt5",
    owned: "No",
    country: "Brunei Darussalam",
    state: null,
    city: "vdvdv",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "No ",
    km: "23244",
    kmacc: "Yes",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "window sticky",
    moreDescription: "xdsfghb",
    reserve: "No",
    hereFrom: "sdffgg",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-06T09:46:54.000000Z",
    updated_at: "2023-01-06T09:46:54.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 34346,
    consignment: "No",
    email: "dfedf2@grfg",
    odmeter: "23244",
    Interstellar: "No",
    interior: "No",
    brandandmodel: "dyffikd",
    sizetires: "205/12rtred",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "ggythg",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/11, 15:18:49",
    pickOne: "tyfyf",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "General listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 23,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T13:26:45.000000Z",
    updated_at: "2023-01-07T13:26:45.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 24,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T13:27:19.000000Z",
    updated_at: "2023-01-07T13:27:19.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 25,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T14:03:20.000000Z",
    updated_at: "2023-01-07T14:03:20.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 26,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T14:03:43.000000Z",
    updated_at: "2023-01-07T14:03:43.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 27,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T14:04:22.000000Z",
    updated_at: "2023-01-07T14:04:22.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 28,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T14:04:51.000000Z",
    updated_at: "2023-01-07T14:04:51.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 29,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T14:05:29.000000Z",
    updated_at: "2023-01-07T14:05:29.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 30,
    userId: null,
    name: null,
    year: null,
    make: null,
    description: null,
    model: null,
    owned: null,
    country: null,
    state: null,
    city: null,
    bat: null,
    batDescription: null,
    dealerName: null,
    dealerId: null,
    dealerDescription: null,
    ownerDetail: null,
    km: null,
    kmacc: null,
    ogEngine: null,
    transmission: null,
    title: null,
    titleStatus: null,
    engineSize: null,
    stepOneImage: null,
    stepTwoImage: null,
    stepThreeImage: null,
    stepFourImage: null,
    link: null,
    accessories: null,
    moreDescription: null,
    reserve: null,
    hereFrom: null,
    ammountOnDocument: null,
    membership: null,
    flag: null,
    created_at: "2023-01-07T14:06:11.000000Z",
    updated_at: "2023-01-07T14:06:11.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: null,
    consignment: null,
    email: null,
    odmeter: null,
    Interstellar: null,
    interior: null,
    brandandmodel: null,
    sizetires: null,
    detailvin: null,
    bodywork: null,
    rustpresent: null,
    modificationstock: null,
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: null,
    accept: null,
    understand: null,
    reservAmount: null,
    truckDetails: null,
    EndTime: null,
    pickOne: null,
    acceptTerms: null,
    understandCondition: null,
    modificationOnTruck: null,
    rustDetails: null,
    truckHistory: null,
    otherStatus: null,
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: null,
    approved: null,
    sold: null,
    displayInAuction: null,
    auctionType: null,
    desc1: "",
    desc2: "",
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 31,
    userId: 8,
    name: "messi",
    year: "2017",
    make: "zara",
    description: "dfvdgrgh",
    model: "qwert",
    owned: "No",
    country: "Australia",
    state: null,
    city: "goia",
    bat: null,
    batDescription: null,
    dealerName: "",
    dealerId: "No",
    dealerDescription: "",
    ownerDetail: "Race Car ",
    km: "33432",
    kmacc: "No",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "./upload/vehicles//Vehicle-1673258395.webp",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records",
    moreDescription: "vdffgrfg",
    reserve: "Yes",
    hereFrom: "fgfgt",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-09T09:59:52.000000Z",
    updated_at: "2023-01-09T09:59:55.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 13234,
    consignment: "Yes",
    email: "reddfdfg@gdfg.cgdf",
    odmeter: "33432",
    Interstellar: "No",
    interior: "Yes",
    brandandmodel: "Ford",
    sizetires: "205/12rt",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "fgfghtj",
    accept: null,
    understand: null,
    reservAmount: 123455,
    truckDetails: "",
    EndTime: "2023/1/14, 15:31:53",
    pickOne: "fe44t45",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "0",
    sold: "1",
    displayInAuction: "Yes",
    auctionType: "General listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: null,
  },
  {
    id: 32,
    userId: 8,
    name: "Ronaldo",
    year: "2018",
    make: "Ferrari",
    description: "cvvdfgdfsd",
    model: "2020",
    owned: "No",
    country: "Denmark",
    state: null,
    city: "lisbon",
    bat: null,
    batDescription: null,
    dealerName: "real",
    dealerId: "Yes",
    dealerDescription: "real",
    ownerDetail: "Race Car ",
    km: "22000",
    kmacc: "Yes",
    ogEngine: "",
    transmission: "",
    title: "",
    titleStatus: "",
    engineSize: "No",
    stepOneImage: "",
    stepTwoImage: "",
    stepThreeImage: null,
    stepFourImage: null,
    link: "",
    accessories: "Service Records",
    moreDescription: "dfgdf",
    reserve: "No",
    hereFrom: "fdfg",
    ammountOnDocument: "",
    membership: null,
    flag: null,
    created_at: "2023-01-09T10:09:21.000000Z",
    updated_at: "2023-01-09T10:09:21.000000Z",
    deleted_at: null,
    premium: 1,
    done: 1,
    documentFee: 5000,
    consignment: "No",
    email: "dfdfv@gfg",
    odmeter: "22000",
    Interstellar: "No",
    interior: "Yes",
    brandandmodel: "audi",
    sizetires: "305/13RI",
    detailvin: null,
    bodywork: "No",
    rustpresent: "No",
    modificationstock: "No",
    truckfromnew: null,
    servicesperformed: null,
    issuesorproblems: "dfdefef",
    accept: null,
    understand: null,
    reservAmount: 0,
    truckDetails: "",
    EndTime: "2023/1/14, 15:41:22",
    pickOne: "Alloy",
    acceptTerms: "1",
    understandCondition: "1",
    modificationOnTruck: "",
    rustDetails: "",
    truckHistory: "",
    otherStatus: "",
    otherTrucktitle: null,
    displayInShowroom: null,
    fuel: "Petrol",
    approved: "1",
    sold: "1",
    displayInAuction: "No",
    auctionType: "Premium listing",
    desc1: null,
    desc2: null,
    currentAmount: null,
    view: 0,
    like: 0,
    status: {
      id: 1,
      title: "Approved",
      desc: "",
      param1: "",
      param2: "",
      param3: "",
      param4: "",
    },
  },
];
const searchResult = (datas) =>
  datas.map((curElem) => {
    return {
      label: (
        <>
          {curElem.make && (
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
              }}
            >
              <span>
                <Link to="/showroom">{curElem.make}</Link>
              </span>
            </div>
          )}
        </>
      ),
    };
  });
const App = () => {
  const [options, setOptions] = useState([]);
  const handleSearch = (value) => {
    const values = value.toLowerCase();
    const filterData = data.filter((item) =>
      item.make ? item.make.toLowerCase().includes(values) : item
    );
    setOptions(value ? searchResult(filterData) : []);
  };
  const onSelect = (value) => {
    console.log("onSelect", value);
  };
  return (
    <div className="searchX">
      <AutoComplete
        dropdownMatchSelectWidth={252}
        style={{
          width: 300,
        }}
        className="searchSec"
        options={options}
        onSelect={onSelect}
        onSearch={handleSearch}
        placeholder="Search.."
      ></AutoComplete>
    </div>
  );
};
export default App;
